services:
  django:
    build:
      context: .
    container_name: "django"
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py collectstatic --no-input &&
      gunicorn SeniorPomidor.wsgi:application --bind 0.0.0.0:8000 --log-level info"
    volumes:
      - static_volume:/usr/src/app/back_static/
      - media_volume:/usr/src/app/back_media/
      - ./:/usr/src/app/

  db:
    image: postgres:alpine
    restart: on-failure
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: "db"

  nginx:
    image: nginx:latest
    container_name: "nginx"
    depends_on:
      - django
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/back_static/
      - media_volume:/usr/src/app/back_media/
      - certbot_certs:/etc/letsencrypt
      - certbot_certs_data:/var/lib/letsencrypt
      - ./letsencrypt_webroot:/var/lib/letsencrypt/webroot

  certbot:
    image: certbot/certbot.latest

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot_certs:/etc/letsencrypt
      - certbot_certs_data:/var/lib/letsencrypt
      - ./letsencrypt_webroot:/var/lib/letsencrypt/webroot
    depends_on:
      - nginx

    

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certbot_certs:
  certbot_certs_data:
