# Generated by Django 5.1.2 on 2024-10-30 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_markmodel_alter_carmodel_mark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='markmodel',
            options={'verbose_name': 'Mark', 'verbose_name_plural': 'Marks'},
        ),
    ]
