# Generated by Django 5.1.2 on 2024-10-30 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_carmodel_options_alter_markmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='mark',
            field=models.ForeignKey(default='No mark', on_delete=django.db.models.deletion.CASCADE, to='cars.markmodel'),
        ),
    ]
