# Generated by Django 5.1.2 on 2024-10-30 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_carmodel_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.markmodel'),
        ),
    ]
